# docker-compose.yml
version: '3.8'  # FIXED: Added quotes around version
services: 
  gobank-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=gobank-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=gobank 
      - DB_NAME=gobank
    depends_on:
      gobank-db:
        condition: service_healthy
  gobank-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gobank
      - POSTGRES_DB=gobank  # ADDED THIS LINE
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
volumes:
  pgdata:
